
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module dflipflop(

	//////INPUT////////
	input signed [18:0]in,
	input clk,

	/////OUTPUT///////
	output reg signed [18:0] out
	);
 
	always @(posedge clk) 
	begin 
		out <= in;
	end 
endmodule 





